---
name: Docker build and push

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'
    paths:
    - 'dockerfiles/**'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile_full
            image: ghcr.io/rheinwerk/azure-pipelines:full
          - dockerfile: Dockerfile_min
            image: ghcr.io/rheinwerk/azure-pipelines:min

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read azure .env
        id: azure_env
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: assets/.env

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: assets
          file: assets/${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.image }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            ${{ steps.azure_env.outputs.content }}
